print ("Reglas para jugar a los Dukes:")
print ("1. Puede haber hasta un maximo de 4 jugadores")
print ("2. El total de cartas se reparten entre todos los jugadores")
print ("3. Empieza quien tiene un numero de cartas impar")
print ("4. Ninguno de los jugadores debe ver sus cartas")
print ("5. El jugador inicia tirando una carta al centro")
print ("6. Todos deben tratar de identificar alguna imagen par de sus propias cartas")
print ("7. Quien la identifica primero pone su carta al centro sobre la primera")
print ("8. Asi continuamente hasta que se agoten las cartas")
print ("9. Gana el primero en tirar todas sus cartas")