print("Paso 1: Preparación")
print("Reúne los suministros necesarios: una escoba, una pala de basura, una bolsa de basura y un recogedor si es necesario.")
print("Retira los objetos grandes del piso, como sillas, mesas pequeñas o cualquier otro obstáculo que pueda dificultar el barrido.")
print("Paso 2: Comienza desde el fondo")
print("Comienza barriendo desde la esquina más alejada de la puerta de la habitación y trabaja hacia la salida. Esto te asegurará que no te quedes atrapando en una esquina y puedas salir fácilmente de la habitación cuando termines.")
print("Paso 3: Usa movimientos largos y firmes")
print("Sujeta la escoba con ambas manos y barre en movimientos largos y firmes, dirigiendo la suciedad y los residuos hacia una esquina de la habitación.")
print("Paso 4: Barre en dirección a la pala de basura")
print("A medida que barres, dirige la suciedad hacia una pala de basura colocada estratégicamente para recoger los desechos. Esto te ayudará a mantener la habitación ordenada y a evitar esparcir la suciedad por toda la habitación.")
print("Paso 5: Repasa los rincones y bordes")
print("Después de barrer la mayor parte de la habitación, asegúrate de repasar los rincones y los bordes donde la suciedad tiende a acumularse. Utiliza la escoba o un trapo para limpiar estas áreas difíciles de alcanzar.")
print("Paso 6: Recoge la basura")
print("Utiliza una pala de basura para recoger la suciedad y los residuos barridos. Deposita la basura en una bolsa de basura y deséchala adecuadamente.")
print("Paso 7: Termina con un repaso final")
print("Para terminar, da un último vistazo a la habitación y asegúrate de que no haya quedado ningún residuo en el suelo. Si es necesario, repasa cualquier área que pueda necesitar un toque final.")
print("¡Y eso es todo! Siguiendo estos pasos, podrás barrer una habitación de manera eficiente y dejarla limpia y ordenada.")